### ISSUE TITLE
Fails to install on FreeBSD

### ISSUE THREAD

**Issue by probonopd** [puzrin/lbprint#1]
```
sudo pkg install npm
sudo npm i lbprint -g

node-pre-gyp ERR! System FreeBSD 12.1-RELEASE-p8
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/lbprint/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/lbprint/node_modules/canvas
node-pre-gyp ERR! node -v v14.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
(...)
2343 verbose lifecycle canvas@2.6.1~install: unsafe-perm in lifecycle false
2344 verbose lifecycle canvas@2.6.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/lbprint/node_modules/canvas/node_modules/.bin:/usr/local/lib/node_modules/lbprint/node_modules/.bin:/usr/local/lib/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/user/bin
2345 verbose lifecycle canvas@2.6.1~install: CWD: /usr/local/lib/node_modules/lbprint/node_modules/canvas
2346 silly lifecycle canvas@2.6.1~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
2347 silly lifecycle canvas@2.6.1~install: Returned: code: 1  signal: null
2348 info lifecycle canvas@2.6.1~install: Failed to exec install script
2349 timing action:install Completed in 824ms
2350 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
2351 timing stage:rollbackFailedOptional Completed in 293ms
2352 timing stage:runTopLevelLifecycles Completed in 10781ms
2353 verbose stack Error: canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
2353 verbose stack Exit status 1
2353 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2353 verbose stack     at EventEmitter.emit (events.js:314:20)
2353 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2353 verbose stack     at ChildProcess.emit (events.js:314:20)
2353 verbose stack     at maybeClose (internal/child_process.js:1047:16)
2353 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
2354 verbose pkgid canvas@2.6.1
2355 verbose cwd /usr/home/user
2356 verbose FreeBSD 12.1-RELEASE-p8
2357 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "lbprint" "-g"
2358 verbose node v14.13.0
2359 verbose npm  v6.14.8
2360 error code ELIFECYCLE
2361 error errno 1
2362 error canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
2362 error Exit status 1
2363 error Failed at the canvas@2.6.1 install script.
2363 error This is probably not a problem with npm. There is likely additional logging output above.
2364 verbose exit [ 1, true ]
```

**Comment by puzrin** [comment]
It uses binary "node-canvas" package. Try to search https://github.com/Automattic/node-canvas#compiling for recipe. This does not depens on me.

Or, if you have choice - install on another OS.

One more tip - if you plan use with P300BT, set font size to not exceed 40px in result (by default it uses max possible size).

**Comment by probonopd** [comment]
Thanks @puzrin. 

```
sudo su
pkg install cairo pango png jpeg giflib
npm install canvas --build-from-source
npm i lbprint -g
```

leads to other errors, but I guess I need to solve those with  https://github.com/Automattic/node-canvas.

https://github.com/Automattic/node-canvas/issues/1724

**Comment by puzrin** [comment]
Let's close then as "foreign"

BTW, in worst case, for dymo you can use https://github.com/computerlyrik/dymoprint, but lbprint has better text to image composer.
