### ISSUE TITLE
lbprint -h error

### ISSUE THREAD

**Issue by pickeld** [puzrin/lbprint#3]
```
root@user:~# lbprint -h
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/lbprint/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by puzrin** [comment]
Just reinstall. It can not find depenency.
